export type Event={id:string;name:string;date:string;place:string;guests:number};
export type Mission={id:string;event:string;role:string;date:string;start:string;end:string;capacity:number;people:{person:string;status:string}[]};
export type State={approval:boolean;events:Event[];missions:Mission[];workshops:{id:string;name:string;date:string;start:string;end:string}[];availability:{person:string;date:string;status:string}[];clocks:{id:string;person:string;mission:string;start:string;end:string|null;pause:number;validated:boolean}[];trips:{id:string;person:string;event:string;date:string;direction:string;driver:boolean;vehicle:string;minutes:number}[];production:{id:string;event:string;recipe:string;quantity:number;done:boolean}[]};
export const people=['Lou Martin','Alex Bernard','Camille Robert'];
export const vehicles=['Fourgon Le Cercle','Utilitaire frigorifique','Véhicule personnel'];
export const recipes=[{id:'r1',name:'Citronnade',unit:'litres',yield:6,ingredients:[['Citron','600 g'],['Sucre','400 g'],['Eau','6 l']],steps:['Presser les citrons.','Dissoudre le sucre, mélanger et réserver au frais.']},{id:'r2',name:'Blinis',unit:'pièces',yield:40,ingredients:[['Farine','500 g'],['Lait','60 cl'],['Œufs','4 pièces']],steps:['Mélanger les ingrédients.','Laisser reposer puis cuire de petites portions.']},{id:'r3',name:'Pickles',unit:'bocaux',yield:4,ingredients:[['Légumes','1 kg'],['Vinaigre','50 cl'],['Eau','50 cl']],steps:['Tailler les légumes.','Verser la marinade chaude et laisser refroidir.']},{id:'r4',name:'Cake citron',unit:'pièces',yield:2,ingredients:[['Farine','400 g'],['Œufs','6 pièces'],['Citron','3 pièces']],steps:['Préparer l’appareil et répartir dans les moules.','Cuire et laisser refroidir.']}];
export function addDays(date:string,n:number){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}
export function laboEvents(s:State,date:string){return s.events.filter(e=>date>=addDays(e.date,-5)&&date<=addDays(e.date,1))}
export function duration(m:Mission){const a=Number(m.start.slice(0,2))*60+Number(m.start.slice(3));let b=Number(m.end.slice(0,2))*60+Number(m.end.slice(3));if(b<=a)b+=1440;return b-a}
export function initialState():State{return {approval:false,events:[{id:'e1',name:'Cocktail des Oliviers',date:'2026-09-10',place:'Villa des Oliviers',guests:80},{id:'e2',name:'Mariage au domaine',date:'2026-09-12',place:'Domaine des Pins',guests:120},{id:'e3',name:'Déjeuner de rentrée',date:'2026-09-19',place:'Maison du Rivage',guests:45}],missions:[{id:'m1',event:'e1',role:'Mise en place',date:'2026-09-09',start:'09:00',end:'15:30',capacity:3,people:[{person:people[0],status:'confirmed'}]},{id:'m2',event:'e2',role:'Mise en place',date:'2026-09-11',start:'09:00',end:'15:30',capacity:3,people:[{person:people[0],status:'confirmed'},{person:people[1],status:'confirmed'}]},{id:'m3',event:'e2',role:'Service',date:'2026-09-12',start:'16:00',end:'00:00',capacity:5,people:[{person:people[0],status:'confirmed'}]},{id:'m4',event:'e1',role:'Service',date:'2026-09-10',start:'17:00',end:'23:00',capacity:4,people:[{person:people[2],status:'confirmed'}]},{id:'m5',event:'e2',role:'Logistique',date:'2026-09-13',start:'09:00',end:'12:00',capacity:2,people:[]},{id:'m6',event:'e3',role:'Chef leader',date:'2026-09-19',start:'08:00',end:'16:00',capacity:1,people:[]}],workshops:[{id:'w1',name:'Atelier pâtisserie',date:'2026-09-23',start:'09:00',end:'12:00'}],availability:[{person:people[0],date:'2026-09-08',status:'Indisponible'}],clocks:[{id:'c1',person:people[0],mission:'m1',start:'2026-09-09T09:00:00',end:'2026-09-09T15:30:00',pause:30,validated:false}],trips:[{id:'t1',person:people[0],event:'e1',date:'2026-09-10',direction:'Aller',driver:true,vehicle:vehicles[0],minutes:80},{id:'t2',person:people[0],event:'e1',date:'2026-09-10',direction:'Retour',driver:false,vehicle:vehicles[0],minutes:80}],production:[{id:'p1',event:'e1',recipe:'r1',quantity:18,done:false},{id:'p2',event:'e2',recipe:'r1',quantity:24,done:false},{id:'p3',event:'e2',recipe:'r2',quantity:240,done:false},{id:'p4',event:'e3',recipe:'r4',quantity:6,done:false}]}}
function requireValue(ok:unknown,message:string):asserts ok{if(!ok)throw Error(message)}
const dateOK=(v:unknown)=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;
const timeOK=(v:unknown)=>typeof v==='string'&&/^([01]\d|2[0-3]):[0-5]\d$/.test(v);
const textOK=(v:unknown)=>typeof v==='string'&&v.trim().length>0&&v.length<=200;
export function transition(old:State,a:any):State{const s:State=structuredClone(old);const id=()=>crypto.randomUUID();requireValue(a&&typeof a.type==='string','Action invalide.');
if(a.type==='approval'){requireValue(typeof a.value==='boolean','Mode invalide.');s.approval=a.value}
else if(a.type==='availability'){requireValue(people.includes(a.person)&&dateOK(a.date)&&['Disponible','Indisponible','À préciser'].includes(a.status),'Disponibilité invalide.');s.availability=s.availability.filter(x=>!(x.person===a.person&&x.date===a.date));s.availability.push({person:a.person,date:a.date,status:a.status})}
else if(a.type==='join'||a.type==='leave'||a.type==='confirm'){const m=s.missions.find(x=>x.id===a.mission);requireValue(m&&people.includes(a.person),'Mission inconnue.');if(a.type==='leave')m.people=m.people.filter(p=>p.person!==a.person);else {requireValue(!s.availability.some(x=>x.person===a.person&&x.date===m.date&&x.status==='Indisponible'),'Vous êtes indisponible à cette date.');const conflicts=s.missions.filter(x=>x.id!==m.id&&x.people.some(p=>p.person===a.person&&p.status==='confirmed'));const start=Date.parse(m.date+'T'+m.start);requireValue(!conflicts.some(x=>{const t=Date.parse(x.date+'T'+x.start);return start<t+duration(x)*60000&&t<start+duration(m)*60000}),'Cette mission chevauche une mission déjà confirmée.');requireValue(m.people.filter(x=>x.status==='confirmed').length<m.capacity,'L’effectif est complet.');const p=m.people.find(x=>x.person===a.person);if(a.type==='confirm'){requireValue(p&&p.status==='pending','Inscription en attente introuvable.');p.status='confirmed'}else{requireValue(!p,'Vous êtes déjà inscrit.');m.people.push({person:a.person,status:s.approval?'pending':'confirmed'})}}}
else if(a.type==='event'){requireValue(textOK(a.name)&&textOK(a.place)&&dateOK(a.date)&&Number.isInteger(a.guests)&&a.guests>0&&a.guests<100000,'Renseignez le nom, le lieu, la date et les convives.');const conflict=s.workshops.find(w=>w.date>=addDays(a.date,-5)&&w.date<=addDays(a.date,1));requireValue(!conflict,'Conflit labo : un atelier est déjà prévu sur la période J−5 à J+1.');s.events.push({id:id(),name:a.name,date:a.date,place:a.place,guests:a.guests})}
else if(a.type==='workshop'){requireValue(textOK(a.name)&&dateOK(a.date)&&timeOK(a.start)&&timeOK(a.end)&&a.end>a.start,'Renseignez un créneau valide.');requireValue(!laboEvents(s,a.date).length,'Le labo est réservé à une prestation sur cette journée.');requireValue(!s.workshops.some(w=>w.date===a.date&&w.start<a.end&&a.start<w.end),'Un atelier occupe déjà ce créneau.');s.workshops.push({id:id(),name:a.name,date:a.date,start:a.start,end:a.end})}
else if(a.type==='mission'){requireValue(s.events.some(e=>e.id===a.event)&&textOK(a.role)&&dateOK(a.date)&&timeOK(a.start)&&timeOK(a.end)&&Number.isInteger(a.capacity)&&a.capacity>0&&a.capacity<100,'Mission invalide.');s.missions.push({id:id(),event:a.event,role:a.role,date:a.date,start:a.start,end:a.end,capacity:a.capacity,people:[]})}
else if(a.type==='clockIn'){requireValue(people.includes(a.person)&&s.missions.some(m=>m.id===a.mission&&m.people.some(p=>p.person===a.person&&p.status==='confirmed')),'Choisissez une mission confirmée.');requireValue(!s.clocks.some(c=>c.person===a.person&&!c.end),'Un pointage est déjà en cours.');s.clocks.push({id:id(),person:a.person,mission:a.mission,start:new Date().toISOString(),end:null,pause:0,validated:false})}
else if(a.type==='clockOut'){const c=s.clocks.find(c=>c.id===a.id&&!c.end);requireValue(c,'Pointage introuvable.');requireValue(Number.isInteger(a.pause)&&a.pause>=0&&a.pause<=(Date.now()-Date.parse(c.start))/60000,'La pause doit être comprise dans le temps de présence.');c.end=new Date().toISOString();c.pause=a.pause}
else if(a.type==='validate'){const c=s.clocks.find(c=>c.id===a.id);requireValue(c&&c.end,'Pointage non terminé.');c.validated=true}
else if(a.type==='trip'){requireValue(people.includes(a.person)&&s.events.some(e=>e.id===a.event)&&dateOK(a.date)&&['Aller','Retour'].includes(a.direction)&&typeof a.driver==='boolean'&&vehicles.includes(a.vehicle)&&Number.isInteger(a.minutes)&&a.minutes>0&&a.minutes<=1440,'Trajet invalide.');s.trips.push({id:id(),person:a.person,event:a.event,date:a.date,direction:a.direction,driver:a.driver,vehicle:a.vehicle,minutes:a.minutes})}
else if(a.type==='production'){requireValue(s.events.some(e=>e.id===a.event)&&recipes.some(r=>r.id===a.recipe)&&Number.isFinite(a.quantity)&&a.quantity>0&&a.quantity<100000,'Quantité ou produit invalide.');s.production.push({id:id(),event:a.event,recipe:a.recipe,quantity:a.quantity,done:false})}
else if(a.type==='produced'){const p=s.production.find(p=>p.id===a.id);requireValue(p,'Production inconnue.');p.done=!p.done}
else throw Error('Action inconnue.');return s}
